"""Progression Agent — aggregated advice and weekly plan generator.

Supports optional LLM enhancement (OpenAI/Anthropic) for natural language advice.
Falls back to rule-based engine when no LLM API key is configured.
"""

import json
import logging
import os

import httpx

from ..models import ProgressionAdvice
from .build_service import get_recommendations
from .progression_service import CURATED_TEMPLATES, generate_goal_plan
from .tp_strategy_service import generate_signals

LLM_API_KEY = os.environ.get("OPENAI_API_KEY") or os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("LLM_API_KEY")
LLM_PROVIDER = os.environ.get("LLM_PROVIDER") or ("openai" if os.environ.get("OPENAI_API_KEY") else ("anthropic" if os.environ.get("ANTHROPIC_API_KEY") else None))

logger = logging.getLogger("gw2.agent")

ACTION_CONFIDENCE = {
    "llm": (0.60, ["llm_response", "gw2_account_snapshot"], "Generated by an LLM from summarized account context; verify before spending gold."),
    "goal": (0.88, ["gw2_account_progression", "curated_goal_templates"], "Goal cost and completion are estimates from current curated templates."),
    "tp": (0.78, ["gw2_tradingpost_signals", "gw2_account_inventory"], "Trading Post opportunities can change quickly with market depth and listing movement."),
    "build": (0.82, ["gw2_account_builds", "curated_build_templates"], "Build readiness is based on curated build templates and detected owned gear."),
    "wallet": (0.95, ["gw2_wallet"], "Wallet-based recommendation uses directly reported liquid gold."),
    "account": (0.75, ["gw2_account_profile"], "Account-wide recommendation is heuristic and should be reviewed against player goals."),
    "routine": (0.70, ["curated_activity_baseline"], "Routine activity estimate is generic and depends on player skill and market prices."),
}


def _with_confidence(action: dict, source: str) -> dict:
    confidence, data_sources, risk_reason = ACTION_CONFIDENCE[source]
    enriched = dict(action)
    enriched.setdefault("confidence", confidence)
    enriched.setdefault("data_sources", data_sources)
    enriched.setdefault("risk_reason", risk_reason)
    return enriched


def _summarize_action_confidence(actions: list[dict]) -> tuple[float, list[str], str]:
    if not actions:
        return 0.0, [], "No recommended actions were generated."
    confidence = round(sum(float(a.get("confidence", 0.0)) for a in actions) / len(actions), 4)
    data_sources = sorted({source for action in actions for source in action.get("data_sources", [])})
    risky = [a for a in actions if float(a.get("confidence", 0.0)) < 0.75]
    risk_reason = f"{len(risky)} recommendations need extra player review." if risky else "Recommendations are based on direct account or curated progression data."
    return confidence, data_sources, risk_reason


def _infer_action_source(action: dict) -> str:
    text = f"{action.get('action', '')} {action.get('target', '')}".lower()
    if "build" in text or "equip" in text:
        return "build"
    if "tradingpost" in text or "sell_items" in text or "buy_opportunities" in text:
        return "tp"
    if "goal" in text:
        return "goal"
    if "wallet" in text or "liquid" in text:
        return "wallet"
    if "daily" in text or "fractals" in text or "activities" in text:
        return "routine"
    return "account"

AGENT_PROMPT = """You are GW2 Progression Advisor, a Guild Wars 2 account progression assistant.
Analyze the account data below and provide personalized advice.

Account Data:
- Name: {account_name}
- Wallet Gold: {wallet_gold}g
- Characters: {character_count}
- Total Skins Unlocked: {skin_count}

Goals (progress toward legendary/ascended items):
{goals_summary}

Trading Post Signals (sell/buy candidates, warnings):
{tp_signals}

Build Readiness (best build matches):
{builds_summary}

Respond with a JSON object (no markdown, no code fences) containing:
1. "summary": A 2-sentence overview of the account
2. "recommended_actions": Array of objects with "action", "target", "reason", "cost" (in copper)
3. "weekly_plan": Array of 7 objects with "day" ("Monday" through "Sunday") and "tasks" (array of strings)

Keep recommendations practical. Prioritize goals with highest completion percentage.
"""


async def _call_llm(prompt: str, credential_key: str | None = None, credential_provider: str | None = None) -> dict | None:
    """Call the configured LLM provider with the prompt. Falls back to env vars if no credential."""
    api_key = credential_key or LLM_API_KEY
    provider = credential_provider or LLM_PROVIDER
    if not api_key or not provider:
        logger.info("No LLM credentials available, skipping LLM call")
        return None

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            if provider == "openai":
                resp = await client.post(
                    "https://api.openai.com/v1/chat/completions",
                    headers={
                        "Authorization": f"Bearer {api_key}",
                        "Content-Type": "application/json",
                    },
                    json={
                        "model": "gpt-4o-mini",
                        "messages": [{"role": "user", "content": prompt}],
                        "temperature": 0.3,
                        "max_tokens": 2000,
                    },
                )
                if resp.status_code != 200:
                    logger.warning("OpenAI API error %d: %s", resp.status_code, resp.text[:200])
                    return None
                content = resp.json()["choices"][0]["message"]["content"]
            elif provider == "anthropic":
                resp = await client.post(
                    "https://api.anthropic.com/v1/messages",
                    headers={
                        "x-api-key": api_key,
                        "anthropic-version": "2023-06-01",
                        "Content-Type": "application/json",
                    },
                    json={
                        "model": "claude-3-5-haiku-latest",
                        "max_tokens": 2000,
                        "messages": [{"role": "user", "content": prompt}],
                    },
                )
                if resp.status_code != 200:
                    logger.warning("Anthropic API error %d: %s", resp.status_code, resp.text[:200])
                    return None
                content = resp.json()["content"][0]["text"]
            else:
                return None

        return _parse_llm_response(content)
    except Exception as e:
        logger.warning("LLM call failed: %s", e)
        return None


def _parse_llm_response(content: str) -> dict | None:
    """Parse LLM response, handling markdown code fences if present."""
    text = content.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        start = 0
        for i, line in enumerate(lines):
            if line.startswith("```"):
                start = i + 1
                break
        end = len(lines)
        for i in range(len(lines) - 1, start - 1, -1):
            if lines[i].strip().startswith("```"):
                end = i
                break
        text = "\n".join(lines[start:end]).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        logger.warning("Failed to parse LLM response as JSON: %.200s", text)
        return None


async def generate_advice(api_key: str) -> ProgressionAdvice:
    from ..analyzer import fetch_all

    contents = await fetch_all(api_key)
    account_name = contents.account_name or "unknown"

    wallet_gold = 0
    for w in contents.wallet or []:
        if w.get("id") == 1:
            wallet_gold = w.get("value", 0)

    advice = ProgressionAdvice(
        summary=f"Account: {account_name}. Wallet: {wallet_gold // 10000}g. Analyzing goals and builds...",
    )

    actions: list[dict] = []
    weekly_plan: list[dict] = []

    # Try LLM first
    goals_summary = ""
    try:
        fastest_goal = None
        for t in CURATED_TEMPLATES[:5]:
            try:
                plan = await generate_goal_plan(api_key, t.template_id)
                if fastest_goal is None or (plan.total_completion_percent > fastest_goal.total_completion_percent and t.difficulty_level != "hard"):
                    fastest_goal = plan
            except Exception:
                continue

        if fastest_goal:
            goals_summary = (
                f"- Best goal: {fastest_goal.template_id} ({fastest_goal.total_completion_percent}% complete, "
                f"{fastest_goal.total_missing_cost // 10000}g remaining, {fastest_goal.total_owned_material_value // 10000}g owned)"
            )
    except Exception as e:
        logger.warning("Goal analysis failed: %s", e)

    tp_summary = ""
    try:
        signals = await generate_signals(account_name)
        sell_count = sum(1 for s in signals if s.signal_type == "sell_candidate")
        buy_count = sum(1 for s in signals if s.signal_type == "buy_candidate")
        warnings_count = sum(1 for s in signals if s.severity == "warning")
        tp_summary = f"- {sell_count} sell candidates, {buy_count} buy opportunities, {warnings_count} warnings"
    except Exception as e:
        logger.warning("Signal generation failed: %s", e)

    builds_summary = ""
    best_build = None
    try:
        recs = await get_recommendations(api_key)
        if recs:
            best_build = recs[0]
            builds_summary = (
                f"- Best build: {best_build.build_name} (readiness: {best_build.readiness_score:.0%}, missing: {best_build.missing_items_count} items, cost: {best_build.missing_cost // 10000}g)"
            )
    except Exception:
        pass

    prompt = AGENT_PROMPT.format(
        account_name=account_name,
        wallet_gold=wallet_gold // 10000,
        character_count=len(contents.characters or []),
        skin_count=contents.unlocked_skins_count or 0,
        goals_summary=goals_summary or "No goals analyzed",
        tp_signals=tp_summary or "No signals available",
        builds_summary=builds_summary or "No builds analyzed",
    )

    # Check for user-saved LLM credentials before calling LLM
    cred_key = None
    cred_provider = None
    try:
        from .credential_service import get_key_by_provider

        for p in ("openai", "anthropic"):
            k = await get_key_by_provider(p)
            if k:
                cred_key = k
                cred_provider = p
                break
    except Exception:
        pass

    llm_result = await _call_llm(prompt, cred_key, cred_provider)

    if llm_result and "recommended_actions" in llm_result:
        advice.summary = llm_result.get("summary", advice.summary)
        for a in llm_result.get("recommended_actions", []):
            actions.append(
                _with_confidence(
                    {
                        "action": a.get("action", "unknown"),
                        "target": a.get("target", ""),
                        "reason": a.get("reason", ""),
                        "cost": a.get("cost", 0),
                    },
                    "llm",
                )
            )
        for day_entry in llm_result.get("weekly_plan", []):
            weekly_plan.append(
                {
                    "day": day_entry.get("day", "Unknown"),
                    "tasks": day_entry.get("tasks", []),
                }
            )
        logger.info("LLM advice generated for %s with %d actions", account_name, len(actions))
    else:
        # Fallback to rule-based engine
        logger.info("Using rule-based fallback for %s", account_name)
        if fastest_goal:
            actions.append(
                _with_confidence(
                    {
                        "action": "continue_goal",
                        "target": fastest_goal.template_id,
                        "reason": f"Goal '{fastest_goal.template_id}' is {fastest_goal.total_completion_percent}% complete, {fastest_goal.total_missing_cost // 10000}g remaining",
                        "cost": fastest_goal.total_missing_cost,
                    },
                    "goal",
                )
            )

        try:
            signals = await generate_signals(account_name)
            sell_signals = [s for s in signals if s.signal_type == "sell_candidate" and s.quantity_owned >= 10]
            for s in sell_signals[:3]:
                actions.append(
                    _with_confidence(
                        {
                            "action": "sell_asset",
                            "target": str(s.item_id),
                            "reason": f"Item #{s.item_id}: {s.quantity_owned}x valued at {s.value_owned // 10000}g, not goal-protected",
                            "cost": s.value_owned,
                        },
                        "tp",
                    )
                )
        except Exception as e:
            logger.warning("Fallback signal generation failed: %s", e)

        if best_build:
            actions.append(
                _with_confidence(
                    {
                        "action": "build_recommendation",
                        "target": best_build.build_id,
                        "reason": f"Best match build: {best_build.build_name} (readiness: {best_build.readiness_score:.0%}, missing: {best_build.missing_items_count} items)",
                        "cost": best_build.missing_cost,
                    },
                    "build",
                )
            )

        days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
        for i, day in enumerate(days):
            entry = {"day": day, "tasks": []}
            if i < len(actions):
                entry["tasks"].append(actions[i]["reason"])
            if i == 0 and actions:
                entry["tasks"].append(f"Review {len(actions)} recommendations")
            weekly_plan.append(entry)

    if not actions:
        actions.append(
            _with_confidence(
                {
                    "action": "run_analysis",
                    "target": "",
                    "reason": "No actionable advice yet. Try creating a goal first.",
                    "cost": 0,
                },
                "account",
            )
        )

    advice.recommended_actions = actions
    advice.weekly_plan = weekly_plan
    advice.confidence, advice.data_sources, advice.risk_reason = _summarize_action_confidence(actions)
    return advice


async def generate_weekly_plan(api_key: str) -> list[dict]:
    advice = await generate_advice(api_key)
    return advice.weekly_plan


async def generate_coach_plan(api_key: str) -> dict:
    """Generate a prioritized, behavior-driven coach plan.

    Returns P0/P1/P2 actions plus a 7-day plan, focused on what the user
    SHOULD DO rather than just displaying data.
    """
    from ..analyzer import fetch_all

    contents = await fetch_all(api_key)
    account_name = contents.account_name or "unknown"

    wallet_gold = 0
    for w in contents.wallet or []:
        if w.get("id") == 1:
            wallet_gold = w.get("value", 0)

    chars = contents.characters or []
    char_count = len(chars)
    lvl80_count = sum(1 for c in chars if c.get("level") == 80)
    professions = set(c.get("profession") for c in chars if c.get("profession"))
    skin_count = contents.unlocked_skins_count or 0

    p0_actions = []
    p1_actions = []
    p2_actions = []

    # P0: Critical path — what makes the biggest difference
    if wallet_gold > 0:
        p0_actions.append(
            _with_confidence(
                {
                    "action": "assess_liquid_assets",
                    "target": "wallet",
                    "reason": f"You have {wallet_gold // 10000}g liquid gold. Review your TP listings for underpriced items.",
                    "gold_impact": wallet_gold // 10000,
                },
                "wallet",
            )
        )
    if lvl80_count < char_count:
        p0_actions.append(
            _with_confidence(
                {
                    "action": "level_characters",
                    "target": "characters",
                    "reason": f"Level {char_count - lvl80_count} characters to 80 to unlock full build potential.",
                    "gold_impact": 0,
                },
                "account",
            )
        )

    # P1: Growth path — meaningful progression
    if skin_count < 200:
        p1_actions.append(
            {
                "action": "unlock_skins",
                "target": "wardrobe",
                "reason": f"Only {skin_count} skins unlocked. Map completion and collections add account value.",
                "gold_impact": skin_count * 10,
            }
        )
    if len(professions) < 5:
        p1_actions.append(
            {
                "action": "try_new_profession",
                "target": "characters",
                "reason": f"Only {len(professions)} professions played. Try a new class to experience more content.",
                "gold_impact": 0,
            }
        )

    # Try fastest goal
    fastest_goal = None
    try:
        for t in CURATED_TEMPLATES[:5]:
            try:
                plan = await generate_goal_plan(api_key, t.template_id)
                if fastest_goal is None or (plan.total_completion_percent > fastest_goal.total_completion_percent and t.difficulty_level != "hard"):
                    fastest_goal = plan
            except Exception:
                continue
    except Exception:
        pass

    if fastest_goal:
        pct = fastest_goal.total_completion_percent
        remaining = fastest_goal.total_missing_cost // 10000
        if pct > 50:
            p0_actions.append(
                {
                    "action": "complete_goal",
                    "target": fastest_goal.template_id,
                    "reason": f"You are {pct:.0f}% done with {fastest_goal.template_id}! Only ~{remaining}g remaining.",
                    "gold_impact": -remaining,
                }
            )
        else:
            p1_actions.append(
                {
                    "action": "start_goal",
                    "target": fastest_goal.template_id,
                    "reason": f"Start working on {fastest_goal.template_id} ({pct:.0f}% complete, ~{remaining}g needed).",
                    "gold_impact": -remaining,
                }
            )

    # Build recommendations
    try:
        from .build_service import get_recommendations

        recs = await get_recommendations(api_key)
        if recs:
            best = recs[0]
            score = best.readiness_score
            if score > 0.7:
                p0_actions.append(
                    {
                        "action": "equip_build",
                        "target": best.build_id,
                        "reason": f"You are {score:.0%} ready for {best.build_name}! Missing {best.missing_items_count} items.",
                        "gold_impact": -best.missing_cost // 10000,
                    }
                )
            elif score > 0.3:
                p1_actions.append(
                    {
                        "action": "build_toward",
                        "target": best.build_id,
                        "reason": f"You are {score:.0%} toward {best.build_name}. Prioritize the missing {best.missing_items_count} items.",
                        "gold_impact": -best.missing_cost // 10000,
                    }
                )
    except Exception:
        pass

    # TP signals
    try:
        from .tp_strategy_service import generate_signals

        signals = await generate_signals(account_name)
        sell_signals = [s for s in signals if s.signal_type == "sell_candidate"]
        buy_signals = [s for s in signals if s.signal_type == "buy_candidate"]
        if sell_signals:
            p1_actions.append(
                {
                    "action": "sell_items",
                    "target": "tradingpost",
                    "reason": f"{len(sell_signals)} items are good sell candidates. Review TP signals tab.",
                    "gold_impact": sell_signals[0].estimated_profit // 10000 if hasattr(sell_signals[0], "estimated_profit") else 0,
                }
            )
        if buy_signals:
            p2_actions.append(
                {
                    "action": "buy_opportunities",
                    "target": "tradingpost",
                    "reason": f"{len(buy_signals)} buy opportunities detected. Consider investing.",
                    "gold_impact": buy_signals[0].estimated_profit // 10000 if hasattr(buy_signals[0], "estimated_profit") else 0,
                }
            )
    except Exception:
        pass

    # P2: Nice-to-have improvements
    if wallet_gold < 10000:
        p2_actions.append(
            {
                "action": "earn_gold",
                "target": "fractals",
                "reason": "Low liquid gold. Run T4 Fractals + dailies for steady income (~20g/day).",
                "gold_impact": 140,
            }
        )
    p2_actions.append(
        {
            "action": "daily_routine",
            "target": "activities",
            "reason": "Complete daily achievements and world boss trains for consistent rewards.",
            "gold_impact": 10,
        }
    )

    # Build daily plan
    daily_plan = [
        {"day": "Monday", "focus": "Sell & Liquidate", "tasks": ["Review TP signals", "Sell excess materials", "Consolidate gold"]},
        {"day": "Tuesday", "focus": "Goal Progress", "tasks": ["Farm goal materials", "Complete time-gated crafts", "Check mystic forge recipes"]},
        {"day": "Wednesday", "focus": "Build Gear", "tasks": ["Acquire missing build items", "Run fracs for ascended gear", "Check stat selectable rewards"]},
        {"day": "Thursday", "focus": "Map Completion", "tasks": ["Complete maps for gifts", "Gather volatile magic", "Farm winterberries"]},
        {"day": "Friday", "focus": "Fractal Push", "tasks": ["Run T4 dailies + recs", "Work on fractal masteries", "Sell fractal junk"]},
        {"day": "Saturday", "focus": "WvW / PvP", "tasks": ["Complete weekly WvW/PvP rewards", "Earn skirmish tickets", "Gift of Battle progress"]},
        {"day": "Sunday", "focus": "Review & Plan", "tasks": ["Review week's progress", "Plan next week's goals", "Export weekly report"]},
    ]

    # Add P0 priority indicators
    for a in p0_actions:
        a.update(_with_confidence(a, _infer_action_source(a)))
        a["priority"] = "P0"
    for a in p1_actions:
        a.update(_with_confidence(a, _infer_action_source(a)))
        a["priority"] = "P1"
    for a in p2_actions:
        a.update(_with_confidence(a, _infer_action_source(a)))
        a["priority"] = "P2"

    all_actions = p0_actions + p1_actions + p2_actions
    confidence, data_sources, risk_reason = _summarize_action_confidence(all_actions)

    return {
        "account_name": account_name,
        "summary": f"Coach plan for {account_name}. {len(p0_actions)} critical, {len(p1_actions)} growth, {len(p2_actions)} optional actions.",
        "priorities": {"P0": p0_actions, "P1": p1_actions, "P2": p2_actions},
        "daily_plan": daily_plan,
        "total_p0": len(p0_actions),
        "total_p1": len(p1_actions),
        "total_p2": len(p2_actions),
        "confidence": confidence,
        "data_sources": data_sources,
        "risk_reason": risk_reason,
    }
