from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from gw2_progression.data_acquisition.contract import DataExpansionRecord
from gw2_progression.data_acquisition.persistence import DataExpansionStore


@dataclass(frozen=True)
class RankedCraftOpportunity:
    rank: int
    entity_id: str
    name: str
    score: float
    net_profit: int
    roi: float
    profit_per_output: int
    craft_cost: int
    output_item_id: str
    recipe_id: str | None
    ingredient_item_ids: list[str]
    raw_payload_hash: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "rank": self.rank,
            "entity_id": self.entity_id,
            "name": self.name,
            "score": self.score,
            "net_profit": self.net_profit,
            "roi": self.roi,
            "profit_per_output": self.profit_per_output,
            "craft_cost": self.craft_cost,
            "output_item_id": self.output_item_id,
            "recipe_id": self.recipe_id,
            "ingredient_item_ids": self.ingredient_item_ids,
            "raw_payload_hash": self.raw_payload_hash,
        }


class CraftProfitRanker:
    """Ranks craft-vs-buy opportunities generated by data expansion."""

    def rank(
        self,
        records: list[DataExpansionRecord],
        *,
        limit: int = 25,
        profitable_only: bool = True,
        min_net_profit: int = 0,
        min_roi: float = 0.0,
    ) -> list[RankedCraftOpportunity]:
        opportunities = []
        for record in records:
            if record.entity_type != "craft_profit_opportunity":
                continue
            candidate = self._candidate(record)
            if profitable_only and candidate["net_profit"] <= 0:
                continue
            if candidate["net_profit"] < min_net_profit:
                continue
            if candidate["roi"] < min_roi:
                continue
            opportunities.append(candidate)

        opportunities.sort(key=lambda row: (row["score"], row["net_profit"], row["roi"]), reverse=True)
        return [
            RankedCraftOpportunity(rank=index + 1, **row)
            for index, row in enumerate(opportunities[: max(0, limit)])
        ]

    def rank_from_store(
        self,
        store: DataExpansionStore,
        *,
        limit: int = 25,
        profitable_only: bool = True,
        min_net_profit: int = 0,
        min_roi: float = 0.0,
        record_limit: int = 10000,
    ) -> list[RankedCraftOpportunity]:
        return self.rank(
            store.list_records(limit=record_limit),
            limit=limit,
            profitable_only=profitable_only,
            min_net_profit=min_net_profit,
            min_roi=min_roi,
        )

    def _candidate(self, record: DataExpansionRecord) -> dict[str, Any]:
        payload = record.normalized_payload
        props = payload.get("properties", {}) if isinstance(payload, dict) else {}
        props = props if isinstance(props, dict) else {}
        net_profit = int(props.get("net_profit") or 0)
        roi = float(props.get("roi") or 0.0)
        profit_per_output = int(props.get("profit_per_output") or 0)
        craft_cost = int(props.get("craft_cost") or 0)
        ingredient_ids = props.get("ingredient_item_ids", [])
        if not isinstance(ingredient_ids, list):
            ingredient_ids = []
        return {
            "entity_id": record.entity_id,
            "name": str(payload.get("name") or record.entity_id),
            "score": self._score(net_profit, roi, profit_per_output),
            "net_profit": net_profit,
            "roi": roi,
            "profit_per_output": profit_per_output,
            "craft_cost": craft_cost,
            "output_item_id": str(props.get("output_item_id") or ""),
            "recipe_id": props.get("recipe_id"),
            "ingredient_item_ids": [str(item_id) for item_id in ingredient_ids],
            "raw_payload_hash": record.raw_payload_hash,
        }

    def _score(self, net_profit: int, roi: float, profit_per_output: int) -> float:
        return round(float(net_profit) + (roi * 100.0) + (profit_per_output * 0.25), 4)
