"""initial_schema

Revision ID: 2f2228331462
Revises:
Create Date: 2026-06-23 20:57:47.052449

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '2f2228331462'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
